### ISSUE TITLE
Program crashes when returning from another activity

### ISSUE THREAD

**Issue by dajver** [brightec/ExampleMediaController#5]
When i return from another activity to my video, it crashed with IllegalStateException

on player.prepareAsync();

stack trace:
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.media.MediaPlayer.prepareAsync(Native Method)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at com.videomap.app.dialogs.ViewDataCustomDialog.surfaceCreated(ViewDataCustomDialog.java:497)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.SurfaceView.updateWindow(SurfaceView.java:572)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:232)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.View.dispatchWindowVisibilityChanged(View.java:8004)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1077)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1077)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1077)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1077)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1077)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1077)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1077)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1233)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.Choreographer.doFrame(Choreographer.java:544)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.os.Handler.handleCallback(Handler.java:733)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.os.Handler.dispatchMessage(Handler.java:95)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.os.Looper.loop(Looper.java:136)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at android.app.ActivityThread.main(ActivityThread.java:5001)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at java.lang.reflect.Method.invokeNative(Native Method)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at java.lang.reflect.Method.invoke(Method.java:515)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-12 23:23:05.072: E/AndroidRuntime(24717):    at dalvik.system.NativeStart.main(Native Method)

What I should do to fix this?

**Comment by hadifar** [comment]
Same problem ! any work around ?
I face this problem on Nexus 5 , Android 6

**Comment by amspayam** [comment]
same problem please solve it thanks
